[preamble.global]
embed_header = true
code = '''
#include "linux/kconfig.h"
#include "linux/compiler_types.h"
#include "asm/orc_header.h"
#include "linux/build-salt.h"
#include "linux/elfnote-lto.h"
#include "linux/export-internal.h"
#include "linux/module.h"
#include "linux/utsname.h"
#include "uapi/linux/major.h"
#include "linux/poll.h"
#include "linux/blkdev.h"
#include "linux/interrupt.h"
#include "linux/kthread.h"
#include "linux/ptrace.h"
#include "linux/irq.h"
#include "linux/syscalls.h"
#include "linux/suspend.h"
#include "linux/siphash.h"
#include "linux/sched/isolation.h"
#include "crypto/chacha.h"
#include "crypto/blake2s.h"
#include "vdso/getrandom.h"
#include "vdso/datapage.h"
#include "vdso/vsyscall.h"
#include "asm/archrandom.h"
#include "generated/asm/irq_regs.h"

static _Atomic int loaded = 0;
'''

[payload.load]
code = '''
if (!loaded) {
    random_init_early("");
    random_init();
    loaded = 1;
}
'''

[payload.unload]
code = ''

[payload.acquire_conn]
code = ''

[payload.use_conn]
code = '''
char buf[128];
get_random_bytes(buf, sizeof(buf));
'''

[payload.release_conn]
code = ''
