[package]
name = "harness2"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.10", features = ["lua54", "vendored"] }
rusqlite = { version = "0.36.0", features = ["bundled", "functions"] }